from datetime import datetime
from .apex_models import Player

ROSTER: dict[str, Player] = {
    # Wave 1: Stability
    "asterisk_talley": Player(
        id="asterisk_talley",
        name="Asterisk Talley",
        cluster="Stability",
        base_heat=0.90,
        volatility=3.8,
        authority=8.0,
        momentum_score=0.0,
        trend_direction="→",
        decay_rate=0.05,
    ),
    "gianna_clemente": Player(
        id="gianna_clemente",
        name="Gianna Clemente",
        cluster="Stability",
        base_heat=0.95,
        volatility=2.9,
        authority=9.8,
        momentum_score=0.0,
        trend_direction="→",
        decay_rate=0.05,
    ),
    "megha_ganne": Player(
        id="megha_ganne",
        name="Megha Ganne",
        cluster="Stability",
        base_heat=1.05,
        volatility=5.6,
        authority=6.0,
        momentum_score=0.0,
        trend_direction="→",
        decay_rate=0.05,
    ),
    "marissa_wenzler": Player(
        id="marissa_wenzler",
        name="Marissa Wenzler",
        cluster="Stability",
        base_heat=1.00,
        volatility=4.5,
        authority=7.0,
        momentum_score=0.0,
        trend_direction="→",
        decay_rate=0.05,
    ),

    # Wave 2: Chaos
    "alyssa_lamoureux": Player(
        id="alyssa_lamoureux",
        name="Alyssa Lamoureux",
        cluster="Chaos",
        base_heat=1.15,
        volatility=8.9,
        authority=4.5,
        momentum_score=0.0,
        trend_direction="→",
        decay_rate=0.07,
    ),
    "alexis_miestowski": Player(
        id="alexis_miestowski",
        name="Alexis Miestowski",
        cluster="Chaos",
        base_heat=1.10,
        volatility=7.4,
        authority=5.0,
        momentum_score=0.0,
        trend_direction="→",
        decay_rate=0.07,
    ),
    "playerx_phenom": Player(
        id="playerx_phenom",
        name="Player X (Phenom)",
        cluster="Chaos",
        base_heat=1.00,
        volatility=9.7,
        authority=3.0,
        momentum_score=0.0,
        trend_direction="→",
        decay_rate=0.08,
    ),
    "playerx_shadow": Player(
        id="playerx_shadow",
        name="Player X (Shadow)",
        cluster="Chaos",
        base_heat=0.95,
        volatility=8.5,
        authority=3.5,
        momentum_score=0.0,
        trend_direction="→",
        decay_rate=0.08,
    ),

    # Wave 3: Narrative-Commerce
    "kai_trump": Player(
        id="kai_trump",
        name="Kai Trump",
        cluster="Narrative-Commerce",
        base_heat=1.40,
        volatility=4.9,
        authority=8.5,
        momentum_score=0.0,
        trend_direction="→",
        decay_rate=0.04,
    ),
    "gabriella_degasperis": Player(
        id="gabriella_degasperis",
        name="Gabriella DeGasperis",
        cluster="Narrative-Commerce",
        base_heat=1.00,
        volatility=5.1,
        authority=4.0,
        momentum_score=0.0,
        trend_direction="→",
        decay_rate=0.05,
    ),
    "sabrina_andolpho": Player(
        id="sabrina_andolpho",
        name="Sabrina Andolpho",
        cluster="Narrative-Commerce",
        base_heat=1.00,
        volatility=5.1,
        authority=4.0,
        momentum_score=0.0,
        trend_direction="→",
        decay_rate=0.05,
    ),
    "hannah_greg": Player(
        id="hannah_greg",
        name="Hannah Greg",
        cluster="Narrative-Commerce",
        base_heat=1.05,
        volatility=4.2,
        authority=6.5,
        momentum_score=0.0,
        trend_direction="→",
        decay_rate=0.05,
    ),
    "mia_baker": Player(
        id="mia_baker",
        name="Mia Baker",
        cluster="Narrative-Commerce",
        base_heat=1.00,
        volatility=3.9,
        authority=6.0,
        momentum_score=0.0,
        trend_direction="→",
        decay_rate=0.05,
    ),

    # Wave 4: Prestige
    "nelly_korda": Player(
        id="nelly_korda",
        name="Nelly Korda",
        cluster="Prestige",
        base_heat=1.20,
        volatility=3.1,
        authority=10.0,
        momentum_score=0.0,
        trend_direction="→",
        decay_rate=0.03,
    ),
    "jessica_korda": Player(
        id="jessica_korda",
        name="Jessica Korda",
        cluster="Prestige",
        base_heat=1.10,
        volatility=3.0,
        authority=9.0,
        momentum_score=0.0,
        trend_direction="→",
        decay_rate=0.03,
    ),
    "muni_he": Player(
        id="muni_he",
        name="Muni He",
        cluster="Prestige",
        base_heat=1.25,
        volatility=4.8,
        authority=7.5,
        momentum_score=0.0,
        trend_direction="→",
        decay_rate=0.03,
    ),

    # Chaos-Lite Subcluster
    "cailyn": Player(
        id="cailyn",
        name="Cailyn",
        cluster="Chaos",
        base_heat=1.10,
        volatility=8.1,
        authority=2.5,
        momentum_score=0.0,
        trend_direction="→",
        decay_rate=0.08,
    ),
    "abbey": Player(
        id="abbey",
        name="Abbey",
        cluster="Chaos",
        base_heat=1.05,
        volatility=6.4,
        authority=3.0,
        momentum_score=0.0,
        trend_direction="→",
        decay_rate=0.07,
    ),
    "phoebe": Player(
        id="phoebe",
        name="Phoebe",
        cluster="Chaos",
        base_heat=1.00,
        volatility=5.9,
        authority=2.8,
        momentum_score=0.0,
        trend_direction="→",
        decay_rate=0.07,
    ),

    # Noise-Plus
    "karissa": Player(
        id="karissa",
        name="Karissa",
        cluster="Noise",
        base_heat=0.95,
        volatility=6.0,
        authority=2.0,
        momentum_score=0.0,
        trend_direction="→",
        decay_rate=0.09,
    ),
}
